[default.extend-words]
ACI = "ACI"
[files]
extend-exclude = [
    # This file has a lot of non-English words that trigger false positives
    "/src/content/docs/noctalia-shell/development/plugins/translations.mdx",
]
